// Hôpital M&M — répertoire des médicaments : [nom, DCI, classe, forme & dosage]
export const MEDICAMENTS = [
["Doliprane","Paracétamol","Antalgique","Comprimé 500 mg"],
["Doliprane","Paracétamol","Antalgique","Comprimé 1000 mg"],
["Doliprane","Paracétamol","Antalgique","Sirop enfant 2,4 %"],
["Doliprane","Paracétamol","Antalgique","Suppositoire 150 mg"],
["Dafalgan","Paracétamol","Antalgique","Gélule 500 mg"],
["Efferalgan","Paracétamol","Antalgique","Comprimé effervescent 1 g"],
["Efferalgan Vitamine C","Paracétamol + acide ascorbique","Antalgique","Comprimé effervescent"],
["Dafalgan Codéiné","Paracétamol + codéine","Antalgique","Comprimé 500/30 mg"],
["Ixprim","Tramadol + paracétamol","Antalgique","Comprimé 37,5/325 mg"],
["Topalgic","Tramadol","Antalgique","Gélule 50 mg"],
["Lamaline","Paracétamol + opium + caféine","Antalgique","Gélule"],
["Acupan","Néfopam","Antalgique","Solution injectable 20 mg"],
["Skenan","Morphine","Antalgique","Gélule LP 10 mg"],
["Oramorph","Morphine","Antalgique","Solution buvable 20 mg/ml"],
["Actiskenan","Morphine","Antalgique","Gélule 5 mg"],
["Oxynorm","Oxycodone","Antalgique","Gélule 5 mg"],
["Spasfon","Phloroglucinol","Antalgique","Comprimé lyoc 80 mg"],
["Aspégic","Acide acétylsalicylique","Antalgique","Sachet 1000 mg"],
["Kardégic","Acide acétylsalicylique","Cardiologie","Sachet 75 mg"],
["Advil","Ibuprofène","Anti-inflammatoire","Comprimé 200 mg"],
["Advil","Ibuprofène","Anti-inflammatoire","Suspension buvable enfant 20 mg/ml"],
["Nurofen","Ibuprofène","Anti-inflammatoire","Comprimé 400 mg"],
["Spifen","Ibuprofène","Anti-inflammatoire","Comprimé 400 mg"],
["Antarène","Ibuprofène","Anti-inflammatoire","Comprimé 400 mg"],
["Voltarène","Diclofénac","Anti-inflammatoire","Comprimé LP 75 mg"],
["Voltarène Emulgel","Diclofénac","Anti-inflammatoire","Gel 1 %"],
["Profénid","Kétoprofène","Anti-inflammatoire","Gélule 50 mg"],
["Ketum","Kétoprofène","Anti-inflammatoire","Gel 2,5 %"],
["Bi-Profénid","Kétoprofène","Anti-inflammatoire","Comprimé LP 100 mg"],
["Apranax","Naproxène","Anti-inflammatoire","Comprimé 550 mg"],
["Celebrex","Célécoxib","Anti-inflammatoire","Gélule 200 mg"],
["Solupred","Prednisolone","Anti-inflammatoire","Comprimé orodispersible 20 mg"],
["Cortancyl","Prednisone","Anti-inflammatoire","Comprimé 20 mg"],
["Célestène","Bétaméthasone","Anti-inflammatoire","Solution buvable 0,05 %"],
["Médrol","Méthylprednisolone","Anti-inflammatoire","Comprimé 16 mg"],
["Solumédrol","Méthylprednisolone","Anti-inflammatoire","Poudre injectable 40 mg"],
["Amoxicilline Biogaran","Amoxicilline","Antibiotique","Gélule 500 mg"],
["Clamoxyl","Amoxicilline","Antibiotique","Poudre pour suspension buvable 250 mg/5 ml"],
["Augmentin","Amoxicilline + acide clavulanique","Antibiotique","Comprimé 1 g/125 mg"],
["Augmentin","Amoxicilline + acide clavulanique","Antibiotique","Suspension buvable enfant"],
["Orelox","Cefpodoxime","Antibiotique","Comprimé 100 mg"],
["Oroken","Céfixime","Antibiotique","Comprimé 200 mg"],
["Zinnat","Céfuroxime","Antibiotique","Comprimé 250 mg"],
["Rocéphine","Ceftriaxone","Antibiotique","Poudre injectable 1 g"],
["Zithromax","Azithromycine","Antibiotique","Comprimé 250 mg"],
["Zeclar","Clarithromycine","Antibiotique","Comprimé 500 mg"],
["Pyostacine","Pristinamycine","Antibiotique","Comprimé 500 mg"],
["Oflocet","Ofloxacine","Antibiotique","Comprimé 200 mg"],
["Ciflox","Ciprofloxacine","Antibiotique","Comprimé 500 mg"],
["Tavanic","Lévofloxacine","Antibiotique","Comprimé 500 mg"],
["Bactrim","Sulfaméthoxazole + triméthoprime","Antibiotique","Comprimé forte"],
["Monuril","Fosfomycine","Antibiotique","Sachet 3 g"],
["Furadantine","Nitrofurantoïne","Antibiotique","Gélule 50 mg"],
["Flagyl","Métronidazole","Antibiotique","Comprimé 500 mg"],
["Dalacine","Clindamycine","Antibiotique","Gélule 300 mg"],
["Vibramycine","Doxycycline","Antibiotique","Comprimé 100 mg"],
["Tobrex","Tobramycine","Ophtalmologie","Collyre 0,3 %"],
["Fucithalmic","Acide fusidique","Ophtalmologie","Gel ophtalmique 1 %"],
["Azyter","Azithromycine","Ophtalmologie","Collyre unidose"],
["Dacryoserum","Acide borique + borate de sodium","Ophtalmologie","Solution pour lavage oculaire"],
["Larmes artificielles","Hypromellose","Ophtalmologie","Collyre"],
["Opticron","Cromoglicate de sodium","Ophtalmologie","Collyre 2 %"],
["Xalatan","Latanoprost","Ophtalmologie","Collyre 0,005 %"],
["Fucidine","Acide fusidique","Dermatologie","Crème 2 %"],
["Mupiderm","Mupirocine","Dermatologie","Pommade 2 %"],
["Biafine","Trolamine","Dermatologie","Émulsion"],
["Bépanthen","Dexpanthénol","Dermatologie","Pommade 5 %"],
["Cicalfate","Sulfate de cuivre et zinc","Dermatologie","Crème réparatrice"],
["Dexeryl","Glycérol + vaseline + paraffine","Dermatologie","Crème"],
["Diprosone","Bétaméthasone","Dermatologie","Crème 0,05 %"],
["Tridésonit","Désonide","Dermatologie","Crème 0,05 %"],
["Locapred","Désonide","Dermatologie","Crème 0,1 %"],
["Pevaryl","Éconazole","Dermatologie","Crème 1 %"],
["Lamisil","Terbinafine","Dermatologie","Crème 1 %"],
["Mycoster","Ciclopirox","Dermatologie","Crème 1 %"],
["Aciclovir","Aciclovir","Dermatologie","Crème 5 %"],
["Zovirax","Aciclovir","Antiviral","Comprimé 200 mg"],
["Zelitrex","Valaciclovir","Antiviral","Comprimé 500 mg"],
["Tamiflu","Oséltamivir","Antiviral","Gélule 75 mg"],
["Bétadine dermique","Povidone iodée","Dermatologie","Solution 10 %"],
["Dakin","Hypochlorite de sodium","Dermatologie","Solution pour application cutanée"],
["Chlorhexidine","Chlorhexidine","Dermatologie","Solution aqueuse 0,05 %"],
["Hexomédine","Hexamidine","Dermatologie","Solution 0,1 %"],
["Éosine","Éosine disodique","Dermatologie","Solution aqueuse 2 %"],
["Sérum physiologique","Chlorure de sodium","ORL / Respiratoire","Unidoses 5 ml"],
["Stérimar","Eau de mer","ORL / Respiratoire","Spray nasal"],
["Physiomer","Eau de mer","ORL / Respiratoire","Spray nasal"],
["Prorhinel","Benzododécinium","ORL / Respiratoire","Solution nasale"],
["Nasonex","Mométasone","ORL / Respiratoire","Suspension nasale 50 µg"],
["Avamys","Fluticasone","ORL / Respiratoire","Spray nasal 27,5 µg"],
["Derinox","Naphazoline + prednisolone","ORL / Respiratoire","Solution nasale"],
["Humex Rhume","Paracétamol + pseudoéphédrine","ORL / Respiratoire","Comprimé"],
["Actifed Rhume","Paracétamol + pseudoéphédrine","ORL / Respiratoire","Comprimé"],
["Otipax","Phénazone + lidocaïne","ORL / Respiratoire","Gouttes auriculaires"],
["Oflocet auriculaire","Ofloxacine","ORL / Respiratoire","Solution auriculaire"],
["Polydexa","Néomycine + polymyxine + dexaméthasone","ORL / Respiratoire","Gouttes auriculaires"],
["Strepsils","Amylmétacrésol + alcool dichlorobenzylique","ORL / Respiratoire","Pastille"],
["Lysopaïne","Lysozyme + bacitracine","ORL / Respiratoire","Comprimé à sucer"],
["Drill","Chlorhexidine + tétracaïne","ORL / Respiratoire","Pastille"],
["Toplexil","Oxomémazine","ORL / Respiratoire","Sirop 0,33 mg/ml"],
["Hélicidine","Hélicidine","ORL / Respiratoire","Sirop"],
["Humex toux sèche","Dextrométhorphane","ORL / Respiratoire","Sirop"],
["Mucomyst","Acétylcystéine","ORL / Respiratoire","Sachet 200 mg"],
["Fluimucil","Acétylcystéine","ORL / Respiratoire","Comprimé effervescent 600 mg"],
["Bisolvon","Bromhexine","ORL / Respiratoire","Comprimé 8 mg"],
["Ventoline","Salbutamol","ORL / Respiratoire","Suspension pour inhalation 100 µg"],
["Bricanyl","Terbutaline","ORL / Respiratoire","Turbuhaler 500 µg"],
["Flixotide","Fluticasone","ORL / Respiratoire","Suspension pour inhalation 125 µg"],
["Seretide","Salmétérol + fluticasone","ORL / Respiratoire","Diskus 50/250 µg"],
["Symbicort","Budésonide + formotérol","ORL / Respiratoire","Turbuhaler 200/6 µg"],
["Pulmicort","Budésonide","ORL / Respiratoire","Suspension pour nébulisation 0,5 mg"],
["Atrovent","Ipratropium","ORL / Respiratoire","Solution pour nébulisation 0,5 mg"],
["Singulair","Montélukast","ORL / Respiratoire","Comprimé 10 mg"],
["Spiriva","Tiotropium","ORL / Respiratoire","Gélule pour inhalation 18 µg"],
["Aerius","Desloratadine","Antihistaminique","Comprimé 5 mg"],
["Aerius","Desloratadine","Antihistaminique","Solution buvable 0,5 mg/ml"],
["Clarityne","Loratadine","Antihistaminique","Comprimé 10 mg"],
["Zyrtec","Cétirizine","Antihistaminique","Comprimé 10 mg"],
["Xyzall","Lévocétirizine","Antihistaminique","Comprimé 5 mg"],
["Kestin","Ébastine","Antihistaminique","Comprimé 10 mg"],
["Telfast","Fexofénadine","Antihistaminique","Comprimé 180 mg"],
["Polaramine","Dexchlorphéniramine","Antihistaminique","Comprimé 2 mg"],
["Atarax","Hydroxyzine","Antihistaminique","Comprimé 25 mg"],
["Anapen","Adrénaline","Urgence","Stylo auto-injecteur 0,3 mg"],
["Epipen","Adrénaline","Urgence","Stylo auto-injecteur 0,15 mg"],
["Adrénaline","Adrénaline","Urgence","Solution injectable 1 mg/ml"],
["Glucagen","Glucagon","Urgence","Kit injectable 1 mg"],
["Naloxone","Naloxone","Urgence","Solution injectable 0,4 mg"],
["Nalscue","Naloxone","Urgence","Solution pour pulvérisation nasale"],
["Buccolam","Midazolam","Urgence","Solution buccale 5 mg"],
["Valium","Diazépam","Psychiatrie / Neurologie","Solution injectable 10 mg"],
["Rivotril","Clonazépam","Psychiatrie / Neurologie","Solution buvable 2,5 mg/ml"],
["Natispray","Trinitrine","Cardiologie","Spray sublingual 0,30 mg"],
["Smecta","Diosmectite","Digestif","Sachet 3 g"],
["Tiorfan","Racécadotril","Digestif","Gélule 100 mg"],
["Tiorfan","Racécadotril","Digestif","Sachet nourrisson 10 mg"],
["Imodium","Lopéramide","Digestif","Gélule 2 mg"],
["Adiaril","Soluté de réhydratation orale","Digestif","Sachet"],
["Fanolyte","Soluté de réhydratation orale","Digestif","Sachet"],
["Ultra-levure","Saccharomyces boulardii","Digestif","Gélule 200 mg"],
["Lactéol","Lactobacillus","Digestif","Gélule"],
["Vogalène","Métopimazine","Digestif","Lyoc 7,5 mg"],
["Motilium","Dompéridone","Digestif","Comprimé 10 mg"],
["Primpéran","Métoclopramide","Digestif","Comprimé 10 mg"],
["Zophren","Ondansétron","Digestif","Comprimé orodispersible 4 mg"],
["Gaviscon","Alginate de sodium + bicarbonate","Digestif","Suspension buvable"],
["Maalox","Hydroxyde d'aluminium + magnésium","Digestif","Comprimé à croquer"],
["Mopral","Oméprazole","Digestif","Gélule 20 mg"],
["Inexium","Ésoméprazole","Digestif","Comprimé 20 mg"],
["Inipomp","Pantoprazole","Digestif","Comprimé 40 mg"],
["Lanzor","Lansoprazole","Digestif","Gélule 30 mg"],
["Azantac","Ranitidine","Digestif","Comprimé 150 mg"],
["Forlax","Macrogol 4000","Digestif","Sachet 10 g"],
["Forlax","Macrogol 4000","Digestif","Sachet enfant 4 g"],
["Movicol","Macrogol + électrolytes","Digestif","Sachet"],
["Duphalac","Lactulose","Digestif","Solution buvable"],
["Microlax","Citrate de sodium + laurylsulfoacétate","Digestif","Solution rectale"],
["Normacol","Sodium phosphate","Digestif","Lavement"],
["Débridat","Trimébutine","Digestif","Comprimé 100 mg"],
["Météospasmyl","Alvérine + siméticone","Digestif","Capsule"],
["Carbosylane","Charbon activé + siméticone","Digestif","Gélule"],
["Dulcolax","Bisacodyl","Digestif","Comprimé 5 mg"],
["Helicobacter Pylera","Bismuth + métronidazole + tétracycline","Digestif","Gélule"],
["Fluvermal","Flubendazole","Digestif","Comprimé 100 mg"],
["Povanyl","Pyrvinium","Digestif","Comprimé 50 mg"],
["Uvedose","Cholécalciférol (vitamine D3)","Vitamines & minéraux","Ampoule buvable 100 000 UI"],
["ZymaD","Cholécalciférol (vitamine D3)","Vitamines & minéraux","Gouttes 10 000 UI/ml"],
["Dedrogyl","Calcifédiol","Vitamines & minéraux","Solution buvable"],
["Cacit D3","Calcium + vitamine D3","Vitamines & minéraux","Sachet 1000 mg/880 UI"],
["Orocal D3","Calcium + vitamine D3","Vitamines & minéraux","Comprimé à sucer"],
["Tardyféron","Sulfate ferreux","Vitamines & minéraux","Comprimé 80 mg"],
["Fumafer","Fumarate ferreux","Vitamines & minéraux","Comprimé 66 mg"],
["Ferrostrane","Férédétate de sodium","Vitamines & minéraux","Sirop enfant"],
["Speciafoldine","Acide folique","Vitamines & minéraux","Comprimé 5 mg"],
["Vitamine B12 Gerda","Cyanocobalamine","Vitamines & minéraux","Solution injectable 1000 µg"],
["Bévitine","Thiamine (vitamine B1)","Vitamines & minéraux","Comprimé 250 mg"],
["Laroscorbine","Acide ascorbique (vitamine C)","Vitamines & minéraux","Comprimé 500 mg"],
["Magné B6","Magnésium + vitamine B6","Vitamines & minéraux","Comprimé"],
["Diffu-K","Chlorure de potassium","Vitamines & minéraux","Gélule 600 mg"],
["Toco 500","Tocophérol (vitamine E)","Vitamines & minéraux","Capsule 500 mg"],
["Fluor Crinex","Fluorure de sodium","Vitamines & minéraux","Solution buvable"],
["Uvestérol ADEC","Vitamines A, D, E, C","Vitamines & minéraux","Solution buvable nourrisson"],
["Glucophage","Metformine","Diabète","Comprimé 850 mg"],
["Stagid","Metformine","Diabète","Comprimé 700 mg"],
["Diamicron","Gliclazide","Diabète","Comprimé LM 60 mg"],
["Amarel","Glimépiride","Diabète","Comprimé 2 mg"],
["Januvia","Sitagliptine","Diabète","Comprimé 100 mg"],
["Janumet","Sitagliptine + metformine","Diabète","Comprimé 50/1000 mg"],
["Forxiga","Dapagliflozine","Diabète","Comprimé 10 mg"],
["Jardiance","Empagliflozine","Diabète","Comprimé 10 mg"],
["Trulicity","Dulaglutide","Diabète","Stylo injectable 1,5 mg"],
["Ozempic","Sémaglutide","Diabète","Stylo injectable 0,5 mg"],
["Victoza","Liraglutide","Diabète","Stylo injectable 6 mg/ml"],
["Lantus","Insuline glargine","Diabète","Stylo SoloStar 100 UI/ml"],
["Toujeo","Insuline glargine","Diabète","Stylo SoloStar 300 UI/ml"],
["Levemir","Insuline détémir","Diabète","Stylo FlexPen 100 UI/ml"],
["Tresiba","Insuline dégludec","Diabète","Stylo FlexTouch 100 UI/ml"],
["Novorapid","Insuline asparte","Diabète","Stylo FlexPen 100 UI/ml"],
["Humalog","Insuline lispro","Diabète","Stylo KwikPen 100 UI/ml"],
["Apidra","Insuline glulisine","Diabète","Stylo SoloStar 100 UI/ml"],
["Resucrage","Glucose","Diabète","Sachet 15 g"],
["Amlor","Amlodipine","Cardiologie","Gélule 5 mg"],
["Loxen","Nicardipine","Cardiologie","Comprimé 20 mg"],
["Coversyl","Périndopril","Cardiologie","Comprimé 5 mg"],
["Triatec","Ramipril","Cardiologie","Gélule 5 mg"],
["Renitec","Énalapril","Cardiologie","Comprimé 20 mg"],
["Cozaar","Losartan","Cardiologie","Comprimé 50 mg"],
["Tareg","Valsartan","Cardiologie","Comprimé 80 mg"],
["Aprovel","Irbésartan","Cardiologie","Comprimé 150 mg"],
["Atacand","Candésartan","Cardiologie","Comprimé 8 mg"],
["Cotareg","Valsartan + hydrochlorothiazide","Cardiologie","Comprimé 80/12,5 mg"],
["Esidrex","Hydrochlorothiazide","Cardiologie","Comprimé 25 mg"],
["Lasilix","Furosémide","Cardiologie","Comprimé 40 mg"],
["Aldactone","Spironolactone","Cardiologie","Comprimé 25 mg"],
["Fludex","Indapamide","Cardiologie","Comprimé LP 1,5 mg"],
["Kredex","Carvédilol","Cardiologie","Comprimé 6,25 mg"],
["Détensiel","Bisoprolol","Cardiologie","Comprimé 10 mg"],
["Cardensiel","Bisoprolol","Cardiologie","Comprimé 2,5 mg"],
["Ténormine","Aténolol","Cardiologie","Comprimé 50 mg"],
["Avlocardyl","Propranolol","Cardiologie","Comprimé 40 mg"],
["Temerit","Nébivolol","Cardiologie","Comprimé 5 mg"],
["Cordarone","Amiodarone","Cardiologie","Comprimé 200 mg"],
["Digoxine Nativelle","Digoxine","Cardiologie","Comprimé 0,25 mg"],
["Entresto","Sacubitril + valsartan","Cardiologie","Comprimé 49/51 mg"],
["Plavix","Clopidogrel","Cardiologie","Comprimé 75 mg"],
["Brilique","Ticagrélor","Cardiologie","Comprimé 90 mg"],
["Eliquis","Apixaban","Cardiologie","Comprimé 5 mg"],
["Xarelto","Rivaroxaban","Cardiologie","Comprimé 20 mg"],
["Pradaxa","Dabigatran","Cardiologie","Gélule 150 mg"],
["Préviscan","Fluindione","Cardiologie","Comprimé 20 mg"],
["Coumadine","Warfarine","Cardiologie","Comprimé 5 mg"],
["Lovenox","Énoxaparine","Cardiologie","Seringue 4000 UI"],
["Innohep","Tinzaparine","Cardiologie","Seringue 10 000 UI"],
["Arixtra","Fondaparinux","Cardiologie","Seringue 2,5 mg"],
["Tahor","Atorvastatine","Cardiologie","Comprimé 20 mg"],
["Crestor","Rosuvastatine","Cardiologie","Comprimé 10 mg"],
["Zocor","Simvastatine","Cardiologie","Comprimé 20 mg"],
["Ezetrol","Ézétimibe","Cardiologie","Comprimé 10 mg"],
["Lévothyrox","Lévothyroxine","Endocrinologie","Comprimé 50 µg"],
["L-Thyroxine Serb","Lévothyroxine","Endocrinologie","Solution buvable 5 µg/goutte"],
["Néomercazole","Carbimazole","Endocrinologie","Comprimé 5 mg"],
["Hydrocortisone Roussel","Hydrocortisone","Endocrinologie","Comprimé 10 mg"],
["Fosamax","Alendronate","Rhumatologie","Comprimé 70 mg"],
["Zyloric","Allopurinol","Rhumatologie","Comprimé 100 mg"],
["Colchicine Opocalcium","Colchicine","Rhumatologie","Comprimé 1 mg"],
["Colchimax","Colchicine + tiémonium","Rhumatologie","Comprimé"],
["Novatrex","Méthotrexate","Rhumatologie","Comprimé 2,5 mg"],
["Plaquenil","Hydroxychloroquine","Rhumatologie","Comprimé 200 mg"],
["Lioresal","Baclofène","Rhumatologie","Comprimé 10 mg"],
["Miorel","Thiocolchicoside","Rhumatologie","Gélule 4 mg"],
["Deroxat","Paroxétine","Psychiatrie / Neurologie","Comprimé 20 mg"],
["Seroplex","Escitalopram","Psychiatrie / Neurologie","Comprimé 10 mg"],
["Zoloft","Sertraline","Psychiatrie / Neurologie","Gélule 50 mg"],
["Prozac","Fluoxétine","Psychiatrie / Neurologie","Gélule 20 mg"],
["Effexor","Venlafaxine","Psychiatrie / Neurologie","Gélule LP 75 mg"],
["Cymbalta","Duloxétine","Psychiatrie / Neurologie","Gélule 60 mg"],
["Norset","Mirtazapine","Psychiatrie / Neurologie","Comprimé 15 mg"],
["Laroxyl","Amitriptyline","Psychiatrie / Neurologie","Solution buvable 40 mg/ml"],
["Xanax","Alprazolam","Psychiatrie / Neurologie","Comprimé 0,25 mg"],
["Lexomil","Bromazépam","Psychiatrie / Neurologie","Comprimé 6 mg"],
["Témesta","Lorazépam","Psychiatrie / Neurologie","Comprimé 1 mg"],
["Séresta","Oxazépam","Psychiatrie / Neurologie","Comprimé 10 mg"],
["Stilnox","Zolpidem","Psychiatrie / Neurologie","Comprimé 10 mg"],
["Imovane","Zopiclone","Psychiatrie / Neurologie","Comprimé 7,5 mg"],
["Circadin","Mélatonine","Psychiatrie / Neurologie","Comprimé LP 2 mg"],
["Donormyl","Doxylamine","Psychiatrie / Neurologie","Comprimé 15 mg"],
["Euphytose","Extraits de plantes","Psychiatrie / Neurologie","Comprimé"],
["Risperdal","Rispéridone","Psychiatrie / Neurologie","Comprimé 1 mg"],
["Zyprexa","Olanzapine","Psychiatrie / Neurologie","Comprimé 5 mg"],
["Abilify","Aripiprazole","Psychiatrie / Neurologie","Comprimé 10 mg"],
["Tercian","Cyamémazine","Psychiatrie / Neurologie","Comprimé 25 mg"],
["Téralithe","Lithium","Psychiatrie / Neurologie","Comprimé 250 mg"],
["Ritaline","Méthylphénidate","Psychiatrie / Neurologie","Comprimé 10 mg"],
["Dépakine","Valproate de sodium","Psychiatrie / Neurologie","Comprimé 500 mg"],
["Keppra","Lévétiracétam","Psychiatrie / Neurologie","Comprimé 500 mg"],
["Lamictal","Lamotrigine","Psychiatrie / Neurologie","Comprimé 100 mg"],
["Tégrétol","Carbamazépine","Psychiatrie / Neurologie","Comprimé LP 200 mg"],
["Lyrica","Prégabaline","Psychiatrie / Neurologie","Gélule 75 mg"],
["Neurontin","Gabapentine","Psychiatrie / Neurologie","Gélule 300 mg"],
["Modopar","Lévodopa + bensérazide","Psychiatrie / Neurologie","Gélule 125 mg"],
["Sinemet","Lévodopa + carbidopa","Psychiatrie / Neurologie","Comprimé 100/10 mg"],
["Aricept","Donépézil","Psychiatrie / Neurologie","Comprimé 5 mg"],
["Relpax","Élétriptan","Psychiatrie / Neurologie","Comprimé 40 mg"],
["Zomig","Zolmitriptan","Psychiatrie / Neurologie","Comprimé 2,5 mg"],
["Imigrane","Sumatriptan","Psychiatrie / Neurologie","Comprimé 50 mg"],
["Tanganil","Acétylleucine","Psychiatrie / Neurologie","Comprimé 500 mg"],
["Mercalm","Diménhydrinate + caféine","Psychiatrie / Neurologie","Comprimé"],
["Nausicalm","Diménhydrinate","Psychiatrie / Neurologie","Sirop enfant"],
["Xatral","Alfuzosine","Urologie","Comprimé LP 10 mg"],
["Omix","Tamsulosine","Urologie","Gélule LP 0,4 mg"],
["Vesicare","Solifénacine","Urologie","Comprimé 5 mg"],
["Uromitexan","Mesna","Urologie","Solution injectable"],
["Spasmine","Valériane + aubépine","Psychiatrie / Neurologie","Comprimé"],
["Leeloo","Lévonorgestrel + éthinylestradiol","Gynécologie","Comprimé"],
["Optimizette","Désogestrel","Gynécologie","Comprimé 75 µg"],
["Norlevo","Lévonorgestrel","Gynécologie","Comprimé 1,5 mg"],
["Utrogestan","Progestérone","Gynécologie","Capsule 100 mg"],
["Gyno-Pevaryl","Éconazole","Gynécologie","Ovule LP 150 mg"],
["Monazol","Sertaconazole","Gynécologie","Ovule 300 mg"],
["Ponstyl","Acide méfénamique","Gynécologie","Gélule 250 mg"],
["Antadys","Flurbiprofène","Gynécologie","Comprimé 100 mg"],
["Emla","Lidocaïne + prilocaïne","Anesthésie","Crème 5 %"],
["Xylocaïne","Lidocaïne","Anesthésie","Solution injectable 1 %"],
["Xylocaïne visqueuse","Lidocaïne","Anesthésie","Gel buccal 2 %"],
["Méopa","Protoxyde d'azote + oxygène","Anesthésie","Gaz pour inhalation"],
["Perfalgan","Paracétamol","Antalgique","Solution pour perfusion 1 g"],
["Chlorure de sodium 0,9 %","Chlorure de sodium","Perfusion","Poche 500 ml"],
["Glucose 5 %","Glucose","Perfusion","Poche 500 ml"],
["Ringer lactate","Électrolytes","Perfusion","Poche 500 ml"],
["Bicarbonate de sodium 1,4 %","Bicarbonate de sodium","Perfusion","Poche 250 ml"],
["Albumine 20 %","Albumine humaine","Perfusion","Flacon 100 ml"],
["Vaccin Infanrix Hexa","DTCaP-Hib-HepB","Vaccins","Suspension injectable"],
["Vaccin Priorix","Rougeole-oreillons-rubéole","Vaccins","Poudre injectable"],
["Vaccin Prevenar 13","Pneumocoque","Vaccins","Suspension injectable"],
["Vaccin Boostrix Tetra","dTcaP","Vaccins","Suspension injectable"],
["Vaccin Gardasil 9","Papillomavirus","Vaccins","Suspension injectable"],
["Vaccin Nimenrix","Méningocoque ACWY","Vaccins","Poudre injectable"],
["Vaccin Vaxigrip Tetra","Grippe","Vaccins","Suspension injectable"],
["Vaccin Comirnaty","Covid-19 ARNm","Vaccins","Dispersion injectable"],
["Vaccin Engerix B","Hépatite B","Vaccins","Suspension injectable"],
["Vaccin Havrix","Hépatite A","Vaccins","Suspension injectable"],
["Vaccin Stamaril","Fièvre jaune","Vaccins","Poudre injectable"],
["Vaccin Beyfortus","Nirsévimab (VRS)","Vaccins","Seringue 50 mg"],
["Camilia","Homéopathie","Pédiatrie","Solution buvable unidose"],
["Delabarre","Tamarin","Pédiatrie","Gel gingival"],
["Calmosine","Extraits de plantes","Pédiatrie","Solution buvable"],
["Doliprane nourrisson","Paracétamol","Pédiatrie","Suppositoire 100 mg"],
["Advil enfant","Ibuprofène","Pédiatrie","Suspension buvable 20 mg/ml"],
["Josacine","Josamycine","Pédiatrie","Granulés pour suspension buvable"],
["Clamoxyl enfant","Amoxicilline","Pédiatrie","Suspension buvable 500 mg/5 ml"],
["Célestène enfant","Bétaméthasone","Pédiatrie","Gouttes 0,05 %"],
["Oxyplastine","Oxyde de zinc","Pédiatrie","Pâte dermique"],
["Mitosyl","Oxyde de zinc + huile de foie de poisson","Pédiatrie","Pommade"],
["Pansement Mercurochrome","Pansement adhésif","Petits soins","Boîte de 20"],
["Compresses stériles","Non tissé","Petits soins","Sachet 10 × 10 cm"],
["Bande Velpeau","Bande de crêpe","Petits soins","Rouleau 7 cm × 4 m"],
["Strips","Sutures adhésives","Petits soins","Pochette"],
["Arnica","Arnica montana","Petits soins","Gel"],
["Hémoclar","Pentosane polysulfate","Petits soins","Crème 0,5 %"],
["Poche de froid","Gel réfrigérant","Petits soins","Poche réutilisable"],
["Tulle gras","Tulle imprégné","Petits soins","Pansement 10 × 10 cm"],
["Sirop de grenadine","Sucre + arôme","Maison M&M","Sirop · 1 cuillère"],
["Câlin","Affection","Maison M&M","Illimité"],
["Bisou magique","Affection","Maison M&M","Application locale"],
["Repos sur le canapé","Repos","Maison M&M","Durée à préciser"],
["Tisane de maman","Camomille + miel","Maison M&M","Tasse tiède"],
["Paracétamol IV","Paracétamol","Injectable / IV","Poche 1 g/100 ml"],
["Perfalgan","Paracétamol","Injectable / IV","Flacon 500 mg/50 ml (enfant)"],
["Acupan IV","Néfopam","Injectable / IV","Ampoule 20 mg/2 ml"],
["Profénid IV","Kétoprofène","Injectable / IV","Poudre 100 mg"],
["Tramadol IV","Tramadol","Injectable / IV","Ampoule 100 mg/2 ml"],
["Morphine IV","Morphine","Injectable / IV","Ampoule 10 mg/1 ml"],
["Sufentanil","Sufentanil","Injectable / IV","Ampoule 50 µg/10 ml"],
["Fentanyl","Fentanyl","Injectable / IV","Ampoule 100 µg/2 ml"],
["Kétamine","Kétamine","Injectable / IV","Flacon 50 mg/5 ml"],
["Propofol","Propofol","Injectable / IV","Émulsion 1 % 20 ml"],
["Spasfon IV","Phloroglucinol","Injectable / IV","Ampoule 40 mg/4 ml"],
["Primpéran IV","Métoclopramide","Injectable / IV","Ampoule 10 mg/2 ml"],
["Zophren IV","Ondansétron","Injectable / IV","Ampoule 4 mg/2 ml"],
["Droleptan","Dropéridol","Injectable / IV","Ampoule 2,5 mg/1 ml"],
["Inexium IV","Ésoméprazole","Injectable / IV","Poudre 40 mg"],
["Solumédrol IV","Méthylprednisolone","Injectable / IV","Poudre 120 mg"],
["Hydrocortisone IV","Hydrocortisone","Injectable / IV","Poudre 100 mg"],
["Polaramine IV","Dexchlorphéniramine","Injectable / IV","Ampoule 5 mg/1 ml"],
["Augmentin IV","Amoxicilline + acide clavulanique","Injectable / IV","Poudre 1 g/200 mg"],
["Amoxicilline IV","Amoxicilline","Injectable / IV","Poudre 1 g"],
["Rocéphine IV","Ceftriaxone","Injectable / IV","Poudre 2 g"],
["Claforan","Céfotaxime","Injectable / IV","Poudre 1 g"],
["Tazocilline","Pipéracilline + tazobactam","Injectable / IV","Poudre 4 g/500 mg"],
["Gentamicine","Gentamicine","Injectable / IV","Ampoule 80 mg/2 ml"],
["Vancomycine","Vancomycine","Injectable / IV","Poudre 500 mg"],
["Flagyl IV","Métronidazole","Injectable / IV","Poche 500 mg/100 ml"],
["Aciclovir IV","Aciclovir","Injectable / IV","Poudre 250 mg"],
["Lasilix IV","Furosémide","Injectable / IV","Ampoule 20 mg/2 ml"],
["Loxen IV","Nicardipine","Injectable / IV","Ampoule 10 mg/10 ml"],
["Cordarone IV","Amiodarone","Injectable / IV","Ampoule 150 mg/3 ml"],
["Atropine","Atropine","Injectable / IV","Seringue 0,5 mg"],
["Noradrénaline","Noradrénaline","Injectable / IV","Ampoule 8 mg/4 ml"],
["Dobutamine","Dobutamine","Injectable / IV","Flacon 250 mg/20 ml"],
["Héparine sodique","Héparine","Injectable / IV","Flacon 25 000 UI/5 ml"],
["Exacyl","Acide tranexamique","Injectable / IV","Ampoule 0,5 g/5 ml"],
["Vitamine K1","Phytoménadione","Injectable / IV","Ampoule 10 mg/1 ml"],
["Chlorure de potassium","Chlorure de potassium","Injectable / IV","Ampoule 10 % 10 ml"],
["Sulfate de magnésium","Magnésium","Injectable / IV","Ampoule 15 % 10 ml"],
["Gluconate de calcium","Calcium","Injectable / IV","Ampoule 10 % 10 ml"],
["Glucose 30 %","Glucose","Injectable / IV","Ampoule 10 ml"],
["Glucose 10 %","Glucose","Injectable / IV","Poche 500 ml"],
["Glucosé 5 % + NaCl","Glucose + électrolytes","Injectable / IV","Poche 1 000 ml"],
["Chlorure de sodium 0,9 %","Chlorure de sodium","Injectable / IV","Poche 1 000 ml"],
["Chlorure de sodium 0,9 %","Chlorure de sodium","Injectable / IV","Poche 100 ml (dilution)"],
["Ringer lactate","Électrolytes","Injectable / IV","Poche 1 000 ml"],
["Voluven","Hydroxyéthylamidon","Injectable / IV","Poche 500 ml"],
["Plasmion","Gélatine fluide modifiée","Injectable / IV","Poche 500 ml"],
["Insuline Actrapid IV","Insuline humaine rapide","Injectable / IV","Flacon 100 UI/ml"],
["Naloxone IV","Naloxone","Injectable / IV","Ampoule 0,4 mg/1 ml"],
["Anexate","Flumazénil","Injectable / IV","Ampoule 0,5 mg/5 ml"],
["Fer IV Ferinject","Carboxymaltose ferrique","Injectable / IV","Flacon 500 mg/10 ml"],
["Kit perfusion","Cathéter + tubulure","Injectable / IV","Cathéter 22 G bleu"],
["Kit perfusion","Cathéter + tubulure","Injectable / IV","Cathéter 24 G jaune (enfant)"],
["Pousse-seringue","Seringue 50 ml","Injectable / IV","Débit à régler"],
["Valium","Diazépam","Calmants","Comprimé 2 mg"],
["Valium","Diazépam","Calmants","Comprimé 5 mg"],
["Valium","Diazépam","Calmants","Comprimé 10 mg"],
["Valium","Diazépam","Calmants","Gouttes buvables 1 %"],
["Valium IV","Diazépam","Calmants","Ampoule 10 mg/2 ml"],
["Diazépam rectal","Diazépam","Calmants","Canule rectale 10 mg"],
["Hypnovel","Midazolam","Calmants","Ampoule 5 mg/1 ml"],
["Midazolam","Midazolam","Calmants","Ampoule 5 mg/5 ml"],
["Buccolam","Midazolam","Calmants","Seringue buccale 10 mg"],
["Rivotril","Clonazépam","Calmants","Comprimé 2 mg"],
["Rivotril IV","Clonazépam","Calmants","Ampoule 1 mg/1 ml"],
["Xanax","Alprazolam","Calmants","Comprimé 0,5 mg"],
["Lexomil","Bromazépam","Calmants","Comprimé quadrisécable 6 mg"],
["Témesta","Lorazépam","Calmants","Comprimé 2,5 mg"],
["Séresta","Oxazépam","Calmants","Comprimé 50 mg"],
["Tranxène","Clorazépate","Calmants","Gélule 10 mg"],
["Tranxène IV","Clorazépate","Calmants","Poudre 20 mg"],
["Vératran","Clotiazépam","Calmants","Comprimé 10 mg"],
["Atarax","Hydroxyzine","Calmants","Comprimé 25 mg"],
["Atarax","Hydroxyzine","Calmants","Sirop 2 mg/ml"],
["Atarax IV","Hydroxyzine","Calmants","Ampoule 100 mg/2 ml"],
["Buspar","Buspirone","Calmants","Comprimé 10 mg"],
["Stresam","Étifoxine","Calmants","Gélule 50 mg"],
["Loxapac","Loxapine","Calmants","Ampoule 50 mg/2 ml"],
["Tercian","Cyamémazine","Calmants","Gouttes 40 mg/ml"],
["Nozinan","Lévomépromazine","Calmants","Comprimé 25 mg"],
["Haldol","Halopéridol","Calmants","Ampoule 5 mg/1 ml"],
["Théralène","Alimémazine","Calmants","Sirop 0,05 %"],
["Mélatonine","Mélatonine","Calmants","Comprimé 1 mg"],
["Euphytose","Extraits de plantes","Calmants","Comprimé"],
["Tisane apaisante","Tilleul + verveine","Calmants","Tasse tiède"],
["Doudou","Réconfort","Calmants","Contact prolongé"]
];
